# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(auto_now_add=True)),
                ('log_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamp_date', models.DateField()),
                ('lamp_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('lamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='iot.Lamp')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='iot.Schedule'),
        ),
    ]
